### ISSUE TITLE
prometheus-webhook-snmp-sidecar crash 

### ISSUE THREAD

**Issue by enicdep** [SUSE/prometheus-webhook-snmp#21]
Hi, wondering if you can give an help about this issue.

I'm trying to send snmp alarm outside my cluster, using webhook-snmp.

Webhook-snmp can get the alarms from pm-alert-manager (see webhook_log.txt)
 , but there is crash in sending this alarm outside (at least this is my view) -> see sidecar.txt

Attached also the configmap

[sidecar.txt](https://github.com/SUSE/prometheus-webhook-snmp/files/4451904/sidecar.txt)
[webhook_log.txt](https://github.com/SUSE/prometheus-webhook-snmp/files/4451905/webhook_log.txt)

{"name":"prometheus-webhook-snmp","tags":["v1.1-4-6947fb3a"]}
{"name":"prometheus-webhook-snmp-sidecar","tags":["v0.1-7-6947fb3a"]}

**Comment by votdev** [comment]
This seems to be an `pysnmp` issue. Which version are you using?

**Comment by enicdep** [comment]
It works now !!! I just restarted the POD after editing ConfigMap. 
About the version used:

Package       Version
------------- -------
appdirs       1.4.3
packaging     16.8
pip           10.0.1
ply           3.11
pyasn1        0.4.8
pycryptodomex 3.9.6
pyparsing     2.2.0
pysmi         0.3.4
pysnmp        4.4.12
PyYAML        5.3
setuptools    40.5.0
six           1.11.0
