### ISSUE TITLE
Error when I send a test trame

### ISSUE THREAD

**Issue by crawood** [SUSE/prometheus-webhook-snmp#22]
Hello, 
I have an error when a sent this command for test my server :

curl -X POST -H 'Content-type: application/json' --data '{"receiver": "c-trplv:etcd-alert", "status": "firing", "alerts": [{"status": "firing", "labels": {"alert_name": "Etcd is unavailable", "alert_type": "systemService", "cluster_name": "secure-cluster (ID: c-trplv)", "oid": "1.3.6.1.4.1.50495.15.1.2.3.1", "component_name": "etcd", "group_id": "c-trplv:etcd-alert", "logs": "Get https://x.x.x.x:2379/health: dial tcp x.x.x.x:2379: connect: no route to host", "rule_id": "c-trplv:etcd-alert_etcd-system-service", "severity": "critical"}, "annotations": {}, "startsAt": "2020-05-13T16:38:33.902017076Z", "endsAt": "0001-01-01T00:00:00Z", "generatorURL": ""}]}'  http://xxxxxx.fr:9101 

the solution to unlock my problem is to comment on utils.py line 143 to 148. It's normal ?

Thank you, bye.

**Comment by votdev** [comment]
How does this error look like?

**Comment by votdev** [comment]
I assume it looks like
```
Python 3.8.2 (default, Mar 05 2020, 18:58:42) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pysnmp import hlapi
>>> hlapi.OctetString("asdasd")
<OctetString value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>>, encoding iso-8859-1, payload [asdasd]>
>>> hlapi.OctetString(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/pyasn1/type/univ.py", line 837, in __init__
    base.SimpleAsn1Type.__init__(self, value, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyasn1/type/base.py", line 267, in __init__
    value = self.prettyIn(value)
  File "/usr/lib/python3.8/site-packages/pyasn1/type/univ.py", line 912, in prettyIn
    return bytes(value)
TypeError: cannot convert 'NoneType' object to bytes
```
I can't remember that this happens in the past. Maybe pysnmp has been changed and does not auto-convert `None` to an empty string.

**Comment by crawood** [comment]
Yes, I have the same error

Le jeu. 14 mai 2020 à 12:20, Volker Theile <notifications@github.com> a
écrit :
