### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by gitxbillhub** [SUSE/prometheus-webhook-snmp#24]
Is the docker image available?

**Comment by votdev** [comment]
No, there is currently no Docker image available.

**Comment by mrunge** [comment]
You may want to try https://quay.io/repository/mrunge/prometheus-webhook-snmp
and 
https://github.com/mrunge/prometheus-webhook-snmp/blob/master/Dockerfile

However, there is clearly work to be done.

**Comment by gitxbillhub** [comment]
Will the docker image be available in Docker Hub?

**Comment by votdev** [comment]
> Will the docker image be available in Docker Hub?

I don't think so, but i will check if we can deliver it via https://registry.opensuse.org.

**Comment by mrunge** [comment]
Not exactly docker hub, but it is available via https://quay.io/repository/infrawatch/prometheus-webhook-snmp

**Comment by gitxbillhub** [comment]
Thanks for the prompt reply!

**Comment by gitxbillhub** [comment]
with the docker image, how to we pass parameters to docker image? It seems command "run" has to be in the end in order to work.
`./prometheus-webhook-snmp --debug run --trap-default-severity="warning"` (Not Working)
`./prometheus-webhook-snmp --debug --trap-default-severity="warning" run` (Working)

**Comment by votdev** [comment]
> with the docker image, how to we pass parameters to docker image? It seems command "run" has to be in the end in order to work.
> `./prometheus-webhook-snmp --debug run --trap-default-severity="warning"` (Not Working)
> `./prometheus-webhook-snmp --debug --trap-default-severity="warning" run` (Working)

Use the `/etc/prometheus-webhook-snmp.conf` file.

**Comment by votdev** [comment]
> with the docker image, how to we pass parameters to docker image? It seems command "run" has to be in the end in order to work.
> `./prometheus-webhook-snmp --debug run --trap-default-severity="warning"` (Not Working)
> `./prometheus-webhook-snmp --debug --trap-default-severity="warning" run` (Working)

Fixed with https://github.com/SUSE/prometheus-webhook-snmp/commit/5b4fe413affd46c0d70bb18b70efc05b239f9322. First i wanted to introduce something like this
```
ENV COMMON_ARGS="--debug"
ENV RUN_ARGS=""

CMD exec /usr/bin/prometheus-webhook-snmp $COMMON_ARGS run $RUN_ARGS
```
but finally decided to keep it simple.

**Comment by votdev** [comment]
Sorry, but i switched the behavior of the environment variables with https://github.com/SUSE/prometheus-webhook-snmp/commit/db2dfb09b0e7a1339d92f8b103b3ef3d9067e9be. I think it is better to force `run` argument in the command line.
