### ISSUE TITLE
Rancher -> Icinga alert integration

### ISSUE THREAD

**Issue by Tejeev** [SUSE/prometheus-webhook-snmp#25]
When using the webhook to alert in Icinga from Rancher the alerts are difficult to read as the string get's split up.  This is an important integration for our customer.  

The "High cpu load warning (firing)" is from a custom script running on the customer's side, while everything after the '{' is the alert as recieved.

The expected behavior is an alert composed of a simple string

**Comment by votdev** [comment]
Please open a PR for further discussion of your suggestion.

By the way, doesn't Icinga provide any modification filters? I think i can remember that OSSIM provides the ability to modify incoming data.

**Comment by Tejeev** [comment]
I'm not sure what we should change here to fix this in a PR, but I believe the modification filters may be how they are adding the plain English "High cpu load warning (firing)" message.  Do you have any idea why the message is not being sent as plain text/a single string?

**Comment by votdev** [comment]
It seems Icinga displayes the [prometheusAlertNotificationRawData](https://github.com/SUSE/prometheus-webhook-snmp/blob/master/PROMETHEUS-ALERT-CEPH-MIB.txt#L85) at the end of the message field. Maybe a configuration issue?

**Comment by Tejeev** [comment]
What do you mean a configuration issue?  If Rancher sends a prometheus alert to the webhook, and the webhook reprocesses this for snmp and sends it to Icinga, should it not send a format that Icinga can cleanly display? Or are you saying Rancher Prometheus is not sending an expected format to the webhook?
Is the webhook not sending out a raw JSON string?  I don't work with Icinga, JSON, or SNMP so there are a lot of gaps in my knowledge here.  If I understand correctly we are seeing a raw JSON string in the alert, and it almost seems Icinga is expecting a plain text string it can dump to the UI?

**Comment by votdev** [comment]
>  If I understand correctly we are seeing a raw JSON string in the alert, and it almost seems Icinga is expecting a plain text string it can dump to the UI?

A JSON string is plain text. The raw data is [converted to string](https://github.com/SUSE/prometheus-webhook-snmp/blob/master/prometheus_webhook_snmp/utils.py#L153) when a trap is generated.

> should it not send a format that Icinga can cleanly display?

Why? The MIB explains that [prometheusAlertNotificationRawData](https://github.com/SUSE/prometheus-webhook-snmp/blob/master/PROMETHEUS-ALERT-CEPH-MIB.txt#L85) is a string. If Icinga can't handle that, then it isn't a problem of this webhook.

> What do you mean a configuration issue

IMO it is an Icing (configuration) issue.

**Comment by Tejeev** [comment]
I'm not sure that there would be a configuration that would be able to specircally process a JSON object with all the quotes escaped.
Rancher sends out a JSON object as it's webhook alert, and the webhook appears to be escaping all the quotes before forwarding the alert to Icinga. Is there a way to configure the webhook to stop doing this?

**Comment by votdev** [comment]
I'm sorry, but it is a Icinga issue, the SNMP trap does not contain escaped quotes.
![Bildschirmfoto vom 2020-09-16 09-12-20](https://user-images.githubusercontent.com/1897962/93304185-e4c29c80-f7fc-11ea-9982-738f6efd06a2.png)

**Comment by Tejeev** [comment]
Ah, thank you Volker! 
Do you know if sending the SNMP trap a plain string rather than a JSON object would forward the same to Icinga?  Or do you have a template for a suggested data format?

**Comment by votdev** [comment]
> Do you know if sending the SNMP trap a plain string rather than a JSON object would forward the same to Icinga? Or do you have a template for a suggested data format?

How should the Prometheus alert be packed in a SNMP trap other than in JSON? JSON is the easiest way to transmit structured data and to parse it. The intention of submitting the whole Prometheus alert as part of the SNMP trap is that trap receivers like OSSIM can parse and process additional information of the Prometheus alert which is not submitted as SNMP object.

Please don't expect the data and the format of the SNMP trap this Prometheus receiver sends will be changed just because another software cannot process the SNMP trap correctly.

**Comment by Tejeev** [comment]
Sorry, I think you missunderstand me as I missunderstood you and the technology earlier.  True, this RFE is for a configurable option to pass the data in a different way for the Icinga endpoint, but in my last question I was asking how the SNMP trap would behave if we were able to get Prometheus to send a flat string from our side, or if there were a different data type you would recommend.  I think you are saying there is not (to the latter)?

**Comment by Tejeev** [comment]
I apologize as I am still just figuring out how all this is wired up and my intent is to find the path of least changes/dev hours committed that will result in the customer having a useable alert for their existing infrastructure.

**Comment by votdev** [comment]
You can't change the behavior from outside because the webhook generates the JSON string.
Please see https://github.com/SUSE/prometheus-webhook-snmp/blob/master/prometheus_webhook_snmp/utils.py#L153. At https://github.com/SUSE/prometheus-webhook-snmp/blob/master/prometheus_webhook_snmp/utils.py#L93 you'll see that `rawdata` is the `dict` containing the Prometheus alert.

**Comment by Tejeev** [comment]
Ah, thank you.  Sorry I don't work with code very often at all so it's taken a bit to follow your references.  Ok, I'm working with the customer to look into the Icinga configurations and other tools if needed.  I appreciate your help and patience in this!  Hope you have a wonderful weekend :)
