### ISSUE TITLE
405 http response code with docker image

### ISSUE THREAD

**Issue by gitxbillhub** [SUSE/prometheus-webhook-snmp#29]
Get "405 Method Not Allowed' code when run with docker image
OS: Ubuntu 18.04
Commands:

> docker run quay.io/infrawatch/prometheus-webhook-snmp:latest
> docker exec -it a7843ea53a7a /bin/bash
> curl -I http://localhost:9099/metrics

`HTTP/1.1 405 Method Not Allowed`
`Content-Type: text/html;charset=utf-8`
`Server: CherryPy/18.4.0`
`Date: Mon, 14 Sep 2020 16:57:36 GMT`
`Allow: GET, HEAD`
`Content-Length: 769`

**Comment by votdev** [comment]
You need to run `prometheus-webhook-snmp` with the command line argument `--metrics`.

**Comment by votdev** [comment]
I will close this issue because it is related to an external Docker container which is not maintained by SUSE.

You need to append the `--metrics` argument to https://github.com/infrawatch/prometheus-webhook-snmp/blob/master/Dockerfile#L26.

```
CMD exec /usr/bin/prometheus-webhook-snmp --debug --snmp-port=$SNMP_PORT \
  --snmp-host=$SNMP_HOST --snmp-community=$SNMP_COMMUNITY \
  --alert-oid-label=$ALERT_OID_LABEL run --metrics
```

**Comment by votdev** [comment]
A Docker container maintained by SUSE will be available soonish via https://registry.opensuse.org. See https://build.opensuse.org/package/show/home:vtheile/prometheus-webhook-snmp-image

**Comment by gitxbillhub** [comment]
Thanks votdev. My mistake I didn't realize it's a third-party docker container. I will check out the one from SUSE.
Thanks for the prompt reply.

**Comment by gitxbillhub** [comment]
I noticed the docker link from https://registry.opensuse.org is gone during the weekend. Could you please tell me if you plan to have it back and if you plan to host the docker image somewhere long-term?
Thanks.

**Comment by votdev** [comment]
> I noticed the docker link from [registry.opensuse.org](https://registry.opensuse.org) is gone during the weekend. Could you please tell me if you plan to have it back and if you plan to host the docker image somewhere long-term?
> Thanks.

I don't know how this could happen because the image package has been submitted to the Tumbleweed repo today, so i don't know how it was possible to appear in [registry.opensuse.org](https://registry.opensuse.org/) before. But if the [submission request](https://build.opensuse.org/request/show/835766) has been accepted, the container is available permanently via the [SUSE registry](https://registry.opensuse.org/).

**Comment by gitxbillhub** [comment]
In the request https://build.opensuse.org/request/show/835766
it shows "All the results have state excluded/disabled". Maybe that's the reason?
