### ISSUE TITLE
Issues with starting the container

### ISSUE THREAD

**Issue by oliealex** [SUSE/prometheus-webhook-snmp#36]
Hey,

I'm having some issues starting the container with the default parameters. 

Error:

```DEBUG:prometheus_webhook_snmp.utils:Configuration settings: {"debug": true, "snmp_host": "localhost", "snmp_port": 162, "snmp_community": "private", "snmp_retries": 1, "snmp_timeout": 1, "alert_oid_label": "oid", "trap_oid_prefix": "1.3.6.1.4.1.50495.15", "trap_default_oid": "1.3.6.1.4.1.50495.15.1.2.1", "trap_default_severity": "", "host": "webhook.snmp.com", "port": 9101, "metrics": false}
INFO:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE Listening for SIGTERM.
INFO:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE Listening for SIGHUP.
INFO:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE Listening for SIGUSR1.
INFO:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE Bus STARTING
ERROR:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f0cf53d0b20>>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpserver.py", line 180, in start
    super(Server, self).start()
  File "/usr/lib/python3.8/site-packages/cherrypy/process/servers.py", line 182, in start
    t.start()
  File "/usr/lib64/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

ERROR:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: RuntimeError("can't start new thread")

INFO:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE Bus STOPPING
INFO:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('webhook.snmp.com', 9101)) already shut down
INFO:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE Bus STOPPED
INFO:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE Bus EXITING
INFO:cherrypy.error:[28/Dec/2021:13:24:28] ENGINE Bus EXITED```

**Comment by votdev** [comment]
Which container are you talking about? A self-build container or a container from the openSUSE registry? If the latter one, which version?

**Comment by oliealex** [comment]
The openSUSE registry container, version 1.4. I'm using the default settings except for the host parameter.

**Comment by votdev** [comment]
Sorry, i can not reproduce the issue.
```
$ podman run -p 9099:9099 --env RUN_ARGS="--metrics" registry.opensuse.org/opensuse/prometheus-webhook-snmp:1.4
DEBUG:prometheus_webhook_snmp.utils:Configuration settings: {"debug": true, "snmp_host": "localhost", "snmp_port": 162, "snmp_community": "public", "snmp_retries": 5, "snmp_timeout": 1, "alert_oid_label": "oid", "trap_oid_prefix": "1.3.6.1.4.1.50495.15", "trap_default_oid": "1.3.6.1.4.1.50495.15.1.2.1", "trap_default_severity": "", "host": "0.0.0.0", "port": 9099, "metrics": true}
INFO:cherrypy.error:[29/Dec/2021:08:25:02] ENGINE Listening for SIGTERM.
INFO:cherrypy.error:[29/Dec/2021:08:25:02] ENGINE Listening for SIGHUP.
INFO:cherrypy.error:[29/Dec/2021:08:25:02] ENGINE Listening for SIGUSR1.
INFO:cherrypy.error:[29/Dec/2021:08:25:02] ENGINE Bus STARTING
INFO:cherrypy.error:[29/Dec/2021:08:25:02] ENGINE Serving on http://0.0.0.0:9099
INFO:cherrypy.error:[29/Dec/2021:08:25:02] ENGINE Bus STARTED
INFO:cherrypy.access.139771565969168:10.0.2.100 - - [29/Dec/2021:08:25:10] "GET /metrics HTTP/1.1" 200 802 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"
```

**Comment by oliealex** [comment]
Im using docker in this case, with the version: ```Docker version 20.10.7, build f0df350```
```
sudo docker run -p 9099:9099 --env RUN_ARGS="--metrics" registry.opensuse.org/opensuse/prometheus-webhook-snmp:1.4

DEBUG:prometheus_webhook_snmp.utils:Configuration settings: {"debug": true, "snmp_host": "localhost", "snmp_port": 162, "snmp_community": "public", "snmp_retries": 5, "snmp_timeout": 1, "alert_oid_label": "oid", "trap_oid_prefix": "1.3.6.1.4.1.50495.15", "trap_default_oid": "1.3.6.1.4.1.50495.15.1.2.1", "trap_default_severity": "", "host": "0.0.0.0", "port": 9099, "metrics": true}
INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Listening for SIGTERM.
INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Listening for SIGHUP.
INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Listening for SIGUSR1.
INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Bus STARTING
ERROR:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7fe48cada760>>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpserver.py", line 180, in start
    super(Server, self).start()
  File "/usr/lib/python3.8/site-packages/cherrypy/process/servers.py", line 182, in start
    t.start()
  File "/usr/lib64/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

ERROR:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: RuntimeError("can't start new thread")

INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Bus STOPPING
INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9099)) already shut down
INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Bus STOPPED
INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Bus EXITING
INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Bus EXITED
```

**Comment by votdev** [comment]
> Im using docker in this case, with the version: `Docker version 20.10.7, build f0df350`
> 
> ```
> sudo docker run -p 9099:9099 --env RUN_ARGS="--metrics" registry.opensuse.org/opensuse/prometheus-webhook-snmp:1.4
> 
> DEBUG:prometheus_webhook_snmp.utils:Configuration settings: {"debug": true, "snmp_host": "localhost", "snmp_port": 162, "snmp_community": "public", "snmp_retries": 5, "snmp_timeout": 1, "alert_oid_label": "oid", "trap_oid_prefix": "1.3.6.1.4.1.50495.15", "trap_default_oid": "1.3.6.1.4.1.50495.15.1.2.1", "trap_default_severity": "", "host": "0.0.0.0", "port": 9099, "metrics": true}
> INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Listening for SIGTERM.
> INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Listening for SIGHUP.
> INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Listening for SIGUSR1.
> INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Bus STARTING
> ERROR:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7fe48cada760>>
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 230, in publish
>     output.append(listener(*args, **kwargs))
>   File "/usr/lib/python3.8/site-packages/cherrypy/_cpserver.py", line 180, in start
>     super(Server, self).start()
>   File "/usr/lib/python3.8/site-packages/cherrypy/process/servers.py", line 182, in start
>     t.start()
>   File "/usr/lib64/python3.8/threading.py", line 852, in start
>     _start_new_thread(self._bootstrap, ())
> RuntimeError: can't start new thread
> 
> ERROR:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Shutting down due to error in start listener:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 268, in start
>     self.publish('start')
>   File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 248, in publish
>     raise exc
> cherrypy.process.wspbus.ChannelFailures: RuntimeError("can't start new thread")
> 
> INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Bus STOPPING
> INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9099)) already shut down
> INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Bus STOPPED
> INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Bus EXITING
> INFO:cherrypy.error:[07/Jan/2022:11:33:02] ENGINE Bus EXITED
> ```

Is it possible that this is a network issue? I don't think that the Docker version is the cause. If the container is the same, it should run everywhere.

**Comment by oliealex** [comment]
hmm, maybe. I will try a few different things and see if i can find the issue.

**Comment by oliealex** [comment]
Not sure exactly what the issue, but i have tried different network modes and arguments provided when running the container, however same issue occurs. Googled a bit on the issue and couldn't find anything useful.

**Comment by votdev** [comment]
I'm sorry, but i really can not reproduce your issue.

![Peek 2022-01-10 10-04](https://user-images.githubusercontent.com/1897962/148740956-5d93d3ff-7fe3-4d2a-9054-762e13683c99.gif)

Docker version 20.10.12, build e91ed57

**Comment by worxli** [comment]
I can reproduce the issue:

```
docker run -p 9099:9099 --env RUN_ARGS="--metrics" registry.opensuse.org/opensuse/prometheus-webhook-snmp:1.4
Unable to find image 'registry.opensuse.org/opensuse/prometheus-webhook-snmp:1.4' locally
1.4: Pulling from opensuse/prometheus-webhook-snmp
ac15edbdde31: Pull complete
0566e9fbf758: Pull complete
Digest: sha256:5f016fb9bfb7c6e851320840e4df9852a0fe505daba7dea67eceb78165810ae3
Status: Downloaded newer image for registry.opensuse.org/opensuse/prometheus-webhook-snmp:1.4
DEBUG:prometheus_webhook_snmp.utils:Configuration settings: {"debug": true, "snmp_host": "localhost", "snmp_port": 162, "snmp_community": "public", "snmp_retries": 5, "snmp_timeout": 1, "alert_oid_label": "oid", "trap_oid_prefix": "1.3.6.1.4.1.50495.15", "trap_default_oid": "1.3.6.1.4.1.50495.15.1.2.1", "trap_default_severity": "", "host": "0.0.0.0", "port": 9099, "metrics": true}
INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Listening for SIGTERM.
INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Listening for SIGHUP.
INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Listening for SIGUSR1.
INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Bus STARTING
ERROR:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f39f7edba90>>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpserver.py", line 180, in start
    super(Server, self).start()
  File "/usr/lib/python3.8/site-packages/cherrypy/process/servers.py", line 182, in start
    t.start()
  File "/usr/lib64/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

ERROR:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: RuntimeError("can't start new thread")

INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Bus STOPPING
INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9099)) already shut down
INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Bus STOPPED
INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Bus EXITING
INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Bus EXITED
```

```
 docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by worxli** [comment]
This is really weird because I think I had the exact same container running a few months ago.

**Comment by votdev** [comment]
> I can reproduce the issue:
> 
> ```
> docker run -p 9099:9099 --env RUN_ARGS="--metrics" registry.opensuse.org/opensuse/prometheus-webhook-snmp:1.4
> Unable to find image 'registry.opensuse.org/opensuse/prometheus-webhook-snmp:1.4' locally
> 1.4: Pulling from opensuse/prometheus-webhook-snmp
> ac15edbdde31: Pull complete
> 0566e9fbf758: Pull complete
> Digest: sha256:5f016fb9bfb7c6e851320840e4df9852a0fe505daba7dea67eceb78165810ae3
> Status: Downloaded newer image for registry.opensuse.org/opensuse/prometheus-webhook-snmp:1.4
> DEBUG:prometheus_webhook_snmp.utils:Configuration settings: {"debug": true, "snmp_host": "localhost", "snmp_port": 162, "snmp_community": "public", "snmp_retries": 5, "snmp_timeout": 1, "alert_oid_label": "oid", "trap_oid_prefix": "1.3.6.1.4.1.50495.15", "trap_default_oid": "1.3.6.1.4.1.50495.15.1.2.1", "trap_default_severity": "", "host": "0.0.0.0", "port": 9099, "metrics": true}
> INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Listening for SIGTERM.
> INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Listening for SIGHUP.
> INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Listening for SIGUSR1.
> INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Bus STARTING
> ERROR:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f39f7edba90>>
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 230, in publish
>     output.append(listener(*args, **kwargs))
>   File "/usr/lib/python3.8/site-packages/cherrypy/_cpserver.py", line 180, in start
>     super(Server, self).start()
>   File "/usr/lib/python3.8/site-packages/cherrypy/process/servers.py", line 182, in start
>     t.start()
>   File "/usr/lib64/python3.8/threading.py", line 852, in start
>     _start_new_thread(self._bootstrap, ())
> RuntimeError: can't start new thread
> 
> ERROR:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Shutting down due to error in start listener:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 268, in start
>     self.publish('start')
>   File "/usr/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 248, in publish
>     raise exc
> cherrypy.process.wspbus.ChannelFailures: RuntimeError("can't start new thread")
> 
> INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Bus STOPPING
> INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9099)) already shut down
> INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Bus STOPPED
> INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Bus EXITING
> INFO:cherrypy.error:[12/Jan/2022:18:19:18] ENGINE Bus EXITED
> ```
> 
> ```
>  docker version
> Client: Docker Engine - Community
>  Version:           19.03.13
>  API version:       1.40
>  Go version:        go1.13.15
>  Git commit:        4484c46d9d
>  Built:             Wed Sep 16 17:02:36 2020
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.13
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       4484c46d9d
>   Built:            Wed Sep 16 17:01:06 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.3.7
>   GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
>  runc:
>   Version:          1.0.0-rc10
>   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683
> ```

Please try to upgrade your Docker, i'm running the container with `Docker version 20.10.12, build e91ed57`.

**Comment by worxli** [comment]
Upgrading to 
```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:36 2021
  OS/Arch:          linux/amd64
  Experimental:     false
```

fixed it for me.

**Comment by votdev** [comment]
Updating Docker seems to fix the issue.
