### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by Sunnatillo** [SUSE/prometheus-webhook-snmp#37]
Does  prometheus-webhook-snmp support TLS between aler manager and webhhook? / Do you have any plans to implement it?
If not I would like to work on it

**Comment by kashifest** [comment]
Hi, I think this was added by #38. ANy plans for new release with this change ? 
/cc @votdev

**Comment by votdev** [comment]
> Hi, I think this was added by #38. ANy plans for new release with this change ? /cc @votdev

I'm sorry, but there are no plans to release new container images via SUSE OBS because the project is not used in SES anymore. But you can build the containers on your own.

**Comment by kashifest** [comment]
> > Hi, I think this was added by #38. ANy plans for new release with this change ? /cc @votdev
> 
> I'm sorry, but there are no plans to release new container images via SUSE OBS because the project is not used in SES anymore. But you can build the containers on your own.

I was thinking more about github release, then everyone can build it from release-tag perhaps? Since the repo is not archived yet it would be best to have a release for us users.
